### ISSUE TITLE
geckodriver code 64

### ISSUE THREAD

**Issue by SettingDust** [mozilla/fathom#295]
Due to https://github.com/mozilla/geckodriver/issues/1959. I update `geckodriver` of `fathom_fox` to https://github.com/vladikoff/node-geckodriver/releases/tag/v3.0.1 fix this.
```
Building FathomFox with your ruleset...done.
Running Firefox...Traceback (most recent call last):
  File "d:\applications\scoop\apps\python37\current\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\applications\scoop\apps\python37\current\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Applications\Scoop\apps\python37\current\Scripts\fathom.exe\__main__.py", line 7, in <module>
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\fathom_web\commands\fox.py", line 27, in fox
    with running_firefox(addon_path, True, geckodriver_path):
  File "d:\applications\scoop\apps\python37\current\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\fathom_web\vectorizer.py", line 417, in running_firefox
    service_log_path=devnull,
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    self.service.start()
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "d:\applications\scoop\apps\python37\current\lib\site-packages\selenium\webdriver\common\service.py", line 112, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service C:\Users\setti\AppData\Local\Fathom\Cache\source\22c0b96e\fathom_fox\node_modules\.bin\geckodriver.cmd unexpectedly exited. Status code was: 64
```

**Comment by gregtatum** [comment]
I too am getting this error when going through intro docs, and I'm unable to use Fathom because of it.

**Comment by SettingDust** [comment]
https://github.com/mozilla/fathom/commit/aef041b7d857026f09599d2ad36db1c1ab983987
